[package]
name = "test-rayon"
version = "0.1.0"
authors = ["0xd34db33f <0xd34db33f@noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
debug = true
[dependencies]
rayon = "1.3.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde-humantime = "0.1.1"
humantime = "1.3"
indicatif = {version = "0.13.0", features = ["with_rayon"]}
color-backtrace = "0.3.0"
rand = "0.7.3"
